package com.chape.daoandphp.base.dao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.chape.daoandphp.base.dao.dao.Picurl;

import com.chape.daoandphp.base.dao.dao.PicurlDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig picurlDaoConfig;

    private final PicurlDao picurlDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        picurlDaoConfig = daoConfigMap.get(PicurlDao.class).clone();
        picurlDaoConfig.initIdentityScope(type);

        picurlDao = new PicurlDao(picurlDaoConfig, this);

        registerDao(Picurl.class, picurlDao);
    }
    
    public void clear() {
        picurlDaoConfig.clearIdentityScope();
    }

    public PicurlDao getPicurlDao() {
        return picurlDao;
    }

}
